[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.96"

[dependencies]                                # error handling                                   # helps manage buffers                              # error handling
termion = "4.0.6"

[lints.clippy]
pedantic = "warn"